A = int(input("Enter first number: "))
B = int(input("Enter second number: "))
print(A, "+", B, "=", A+B)
print(A, "-", B, "=", A-B)
print(A, "*", B, "=", A*B)
print(A, "/", B, "=", A/B)
print(A, "%", B, "=", A%B)
print(A, "//", B, "=", A//B)
print(A, "**", B, "=", A**B)
print(A, "==", B, "=", A==B)
print(A, ">=", B, "=", A>=B)
print(A, "<=", B, "=", A<=B)
print(A, "!=", B, "=", A!=B)